### ISSUE TITLE
Implement relaton-calconnect gem based on standards.calconnect.org

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-calconnect#1]
As title.

And the relaton fetch prefix should be `CC`.

**Comment by opoudjis** [comment]
Is this asking for a new gem that is a counterpart to isobib, gbbib, etc, and which screenscrapes calendarstandards.org?

If it is, this gem name breaks the established naming paradigm for all other gems of its type, and that is unacceptable. Please rename to calconnectbib.

**Comment by ronaldtse** [comment]
Instead of screen-scraping this is direct download of Relaton XML files from this site. Does it have to be renamed?

For example 
https://www.calendarstandards.org/standards/csd-publication-process.rxl is a Relaton XML file.

We can also provide a JSON/XML index. Thoughts?

**Comment by opoudjis** [comment]
This can be done by looking for the doc ID in the https://www.calendarstandards.org/standards/ page, and downloading the related Relaton XML file (only when it exists). Doesn't need a separate index.

... But could you get Andrej to do it anyway, just for consistency?

**Comment by ronaldtse** [comment]
The site to fetch from is now https://standards.calconnect.org/

The Relaton XML links are like this:
```
https://standards.calconnect.org/bib/cc-dir-fds-10001-2018.rxl
```

But the HTML links are like this:
```
https://standards.calconnect.org/csd/cc-10001.html
```

I wonder if we should align them to use the same names?

I'm also unsure on whether it is easy to find them. Thoughts @opoudjis ?

@andrew2net could you please help here? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse I'll be back home at 29 January then can help you.

**Comment by opoudjis** [comment]
If this is going to be about finding XML documents based on document identifiers, then cc-10001.xml would be preferable. However, these document should be discovered through screenscraping of the main site anyway, because there might be good reason that a Relaton XML document has been renamed, and not all Calconnect standards are going to have an associated Relaton XML document in the first place. So I don't believe it will make that much difference.

**Comment by ronaldtse** [comment]
We should not be doing any screen scraping since we can create a relaton index in JSON or XML. All CalConnect documents are available through Relaton.

**Comment by opoudjis** [comment]
I'm assigning this to Andrej; and yes, the names for the relaton and the metanorma files should be consistent, with one catch: the Relaton file can refer to the document without reference to stages, while the Metanorma file can still be stage-specific; for example, the Metanorma filename can contain a `-WD-` abbreviation, if it is still in working draft; the Relaton filename can refer to the document without the current stage, in which case it would not contain `-WD-`.

**Comment by ronaldtse** [comment]
@andrew2net @opoudjis when we work on this I want to also align the index of the standards.calconnect.org site to show what we need. This will either be a Relaton collection XML, and/or a JSON index. Is there something called a Relaton JSON index? 😉

**Comment by andrew2net** [comment]
@ronaldtse do you mean we need to create an index of standards.calconnect.org/standards page and save it locally?

**Comment by andrew2net** [comment]
@opoudjis what is relaton/metanorma files?

**Comment by ronaldtse** [comment]
@andrew2net Yes, we will need to create the following pages:

* `standards.calconnect.org/index.json`
* `standards.calconnect.org/index.rxl`

To enable the relaton-calconnect gem to fetch.

**Comment by andrew2net** [comment]
@ronaldtse so are we waiting until the indexes will be created?

**Comment by opoudjis** [comment]
By relaton file, I mean the .rxl file, and by metanorma file, the .XML output of metanorma.

**Comment by opoudjis** [comment]
@ronaldtse shouldn't this too migrate to metanorma?

**Comment by ronaldtse** [comment]
Missed it, doing now.

**Comment by ronaldtse** [comment]
Migrated.

@andrew2net yes, we're waiting for the index to be created. Thanks!

**Comment by ronaldtse** [comment]
@andrew2net the index is now created in https://github.com/CalConnect/standards.calconnect.org/issues/17 .

The Relaton indexes can be accessed here: 
*  ~~YAML index: https://standards.calconnect.org/bibcoll/index.yaml~~
*  ~~RXL index: https://standards.calconnect.org/bibcoll/index.rxl~~

This is now implemented at:

* Relaton XML: https://standards.calconnect.org/relaton/index.rxl
* Relaton YAML: https://standards.calconnect.org/relaton/index.yaml

**Comment by ronaldtse** [comment]
This task should also help migrate the standards.calconnect.org Relaton YAML (old format) data to the new Relaton YAML (new format). Thanks.

**Comment by andrew2net** [comment]
@ronaldtse should we cache the index to reduce HTTP request number?

**Comment by ronaldtse** [comment]
@andrew2net sure, that's fine!

**Comment by andrew2net** [comment]
@ronaldtse in the index rxl link (for example `relaton/xml/cc-dir-10005-2019.rxl`) is different from rxl link (`csd/cc-10005.rxl`) on document page. These links return different XML content:
- link from index returns XML without URIs.
- link from document returns XML without `docnumber`, `version`, and attributes for some nodes (`title`, `docidentifier`)

**Comment by ronaldtse** [comment]
@andrew2net that's not good. Can you please help fix this issue in Relaton (and make a PR to standards.calconnect.org)? The whole standards.calconnect.org site is generated via Relaton.

**Comment by andrew2net** [comment]
@ronaldtse ok, I'll investigate the problem in standards.calconnect.org

**Comment by andrew2net** [comment]
> The whole standards.calconnect.org site is generated via Relaton.

@ronaldtse if the site is generated via relaton why do we need to get the data back to relaton from the site?

**Comment by ronaldtse** [comment]
@andrew2net there are 3 sources of data for standards.calconnect.org:

1. Documents that are not in Metanorma but hosted locally: https://github.com/CalConnect/standards.calconnect.org/blob/master/_input/admin.yaml
2. Externally-hosted documents: (documents that are not located on this portal) https://github.com/CalConnect/standards.calconnect.org/blob/master/_input/external.yaml
3. Documents generated from Metanorma: https://github.com/CalConnect/published-csd/tree/d0f27ba56cc5da6b5256f95f783838e24fe3f345

We need to:

1. Migrate 1 and 2 types into the new Relaton YAML (they're in the old Relaton YAML) format.
2. Fix Relaton index as you mentioned above.

**Comment by andrew2net** [comment]
@ronaldtse in an old YAML `datatype` is empty. The bibliographic grammar doesn't allow empty date type. Should we assign some type or relax the grammar?

**Comment by ronaldtse** [comment]
@andrew2net what is usually put in `datatype`? We could fill that in too...

**Comment by andrew2net** [comment]
@ronaldtse these types are in grammar:
```
BibliographicDateType =
"published" | "accessed" | "created" | "implemented" | "obsoleted" | "confirmed" | "updated" | "issued" | "transmitted" | "copied" | "unchanged" | "circulated" | "adapted"
```

**Comment by ronaldtse** [comment]
I think the dates are just published dates, so just put “published” for all dates. Thanks.

**Comment by andrew2net** [comment]
> @ronaldtse in the index rxl link (for example `relaton/xml/cc-dir-10005-2019.rxl`) is different from rxl link (`csd/cc-10005.rxl`) on document page. These links return different XML content:
> 
> * link from index returns XML without URIs.
> * link from document returns XML without `docnumber`, `version`, and attributes for some nodes (`title`, `docidentifier`)

@ronaldtse as I understand the `rlx` type of url in the `index.yaml` points to a document's metadata:
```yaml
  - docidentifier: CC/DIR 10005:2019
    doctype: directive
    title: Guidelines for the implementation of the CalConnect patent policy
    stage: published
    xml: csd/cc-10005.xml
    pdf: csd/cc-10005.pdf
    doc: csd/cc-10005.doc
    html: csd/cc-10005.html
    rxl: relaton/xml/cc-dir-10005-2019.rxl
    revdate: '2019-06-05'
    technical_committee: PUBLISH
    copyright_from: '2019'
    copyright_owner: CalConnect
    contributor_author_role: ''
    contributor_author_organization: CalConnect
    contributor_publisher_role: ''
    contributor_publisher_organization: CalConnect
    language: en
    script: Latn
    edition: '1'
    datetype: published
```
The metadata is in RXL format and contains the links to all available formats including RXL:
```xml
<bibdata type='directive'>
<fetched>2019-09-30</fetched>
<title>Guidelines for the implementation of the CalConnect patent policy</title>
<docidentifier>CC/DIR 10005:2019</docidentifier>
<uri type='xml'>csd/cc-10005.xml</uri>
<uri type='html'>csd/cc-10005.html</uri>
<uri type='pdf'>csd/cc-10005.pdf</uri>
<uri type='doc'>csd/cc-10005.doc</uri>
<uri type='rxl'>csd/cc-10005.rxl</uri>
<language>en</language>
<script>Latn</script>
<copyright><from>2019</from>
<owner><organization><name>CalConnect</name></organization></owner>
</copyright><contributor>
<role type='author'/>
<organization><name>CalConnect</name></organization>
</contributor>
<contributor>
<role type='publisher'/>
<organization><name>CalConnect</name></organization>
</contributor>
<date type='published'><on>2019-06-05</on></date>
<edition>1</edition>
<language>en</language>
<script>Latn</script>
<status>published</status>
<editorialgroup><technical-committee>PUBLISH</technical-committee></editorialgroup>
</bibdata>
```
To get a document in RXL format we need to make 2 http requests to the server. First to get a document's metadata, second to get document in required format using url form the metadata.
I think we can take links from metadata and add them to a document. Do you agree?

But, not all documents are in RXL format. For example this document from `index.yaml` points to `rxl: relaton/xml/cc-adm-0401-2004.rxl` metadata:
```yaml
...
  - docidentifier: CC/Adm 0401:2004
    doctype: administrative
    title: July 2004 CalConnect Interoperability Test Rules and Test Scenarios V1.0
      (CD 0401)
    stage: published
    pdf: pubdocs/CD0401%20July%202004%20CalConnect%20Interoperability%20Test%20Rules%20and%20Test%20Scenarios%20V1.0.pdf
    rxl: relaton/xml/cc-adm-0401-2004.rxl
    revdate: '2004-07-30'
    technical_committee: IOPTEST
    language: ''
    script: ''
    datetype: ''
...
```
but the metadata contains link to PDF format only:
```xml
<bibdata type='administrative'>
<fetched>2019-09-30</fetched>
<title>July 2004 CalConnect Interoperability Test Rules and Test Scenarios V1.0 (CD 0401)</title>
<docidentifier>CC/Adm 0401:2004</docidentifier>
<uri type='pdf'>pubdocs/CD0401%20July%202004%20CalConnect%20Interoperability%20Test%20Rules%20and%20Test%20Scenarios%20V1.0.pdf</uri>
<language></language>
<script></script>
<date type=''><on>2004-07-30</on></date>
<language></language>
<script></script>
<status>published</status>
<editorialgroup><technical-committee>IOPTEST</technical-committee></editorialgroup>
</bibdata>
```
In last case we can fetch data from the metadata. Is it ok?
